name: schedule

on:
  schedule:
    - cron: "0/5 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: |
          export NOW=$(date '+%Y-%m-%d-%H-%M-%S')
          export DAY=$(date '+%Y-%m-%d')
          export DAY_1d=$(date -d '1 days ago' '+%Y-%m-%d')
          export DAY_3d=$(date -d '3 days ago' '+%Y-%m-%d')
          export DAY_7d=$(date -d '7 days ago' '+%Y-%m-%d')

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Get
        run: ls -alh

      - uses: stefanzweifel/git-auto-commit-action@v5
